{
 "title": "BGP Stats",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "switch",
    "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: v.bucket,\n    tag: \"host\",\n    predicate: (r) => true,\n    start: -1d\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "Prefixes sent",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"gnmi\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"/network_instances/network_instance/protocols/protocol/bgp/neighbors/neighbor/afi_safis/afi_safi/state/prefixes/sent\")\n  |> filter(fn: (r) => r[\"/network-instances/network-instance/protocols/protocol/name\"] == \"BGP\")\n  |> filter(fn: (r) => r[\"_field\"] == \"/network_instances/network_instance/protocols/protocol/bgp/neighbors/neighbor/afi_safis/afi_safi/state/prefixes/sent\")\n  |> filter(fn: (r) => r[\"afi_safi_name\"] == \"IPV4_UNICAST\")\n  |> filter(fn: (r) => r[\"host\"] == \"${switch}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "BGP Prefixes received",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"gnmi\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"/network_instances/network_instance/protocols/protocol/bgp/neighbors/neighbor/afi_safis/afi_safi/state/prefixes/sent\" or r[\"_measurement\"] == \"/network_instances/network_instance/protocols/protocol/bgp/neighbors/neighbor/afi_safis/afi_safi/state/prefixes/received_pre_policy\")\n  |> filter(fn: (r) => r[\"/network-instances/network-instance/protocols/protocol/name\"] == \"BGP\")\n  |> filter(fn: (r) => r[\"_field\"] == \"/network_instances/network_instance/protocols/protocol/bgp/neighbors/neighbor/afi_safis/afi_safi/state/prefixes/received_pre_policy\" or r[\"_field\"] == \"/network_instances/network_instance/protocols/protocol/bgp/neighbors/neighbor/afi_safis/afi_safi/state/prefixes/sent\")\n  |> filter(fn: (r) => r[\"afi_safi_name\"] == \"IPV4_UNICAST\")\n  |> filter(fn: (r) => r[\"host\"] == \"${switch}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Installed BGP Prefixes",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"gnmi\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"/network_instances/network_instance/protocols/protocol/bgp/neighbors/neighbor/afi_safis/afi_safi/state/prefixes/installed\")\n  |> filter(fn: (r) => r[\"/network-instances/network-instance/protocols/protocol/name\"] == \"BGP\")\n  |> filter(fn: (r) => r[\"_field\"] == \"/network_instances/network_instance/protocols/protocol/bgp/neighbors/neighbor/afi_safis/afi_safi/state/prefixes/installed\")\n  |> filter(fn: (r) => r[\"afi_safi_name\"] == \"IPV4_UNICAST\")\n  |> filter(fn: (r) => r[\"host\"] == \"${switch}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Peer AS Numbers",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"gnmi\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"/network_instances/network_instance/protocols/protocol/bgp/neighbors/neighbor/config/peer_as\")\n  |> filter(fn: (r) => r[\"/network-instances/network-instance/protocols/protocol/name\"] == \"BGP\")\n  |> filter(fn: (r) => r[\"_field\"] == \"/network_instances/network_instance/protocols/protocol/bgp/neighbors/neighbor/config/peer_as\")\n  |> filter(fn: (r) => r[\"host\"] == \"${switch}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}