{
 "title": "Interface_Stats Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "switch",
    "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: v.bucket,\n    tag: \"host\",\n    predicate: (r) => true,\n    start: -1d\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "Free memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"gnmi\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"/system/memory/state/physical\" or r[\"_measurement\"] == \"/system/memory/state/reserved\")\n  |> filter(fn: (r) => r[\"_field\"] == \"/system/memory/state/physical\" or r[\"_field\"] == \"/system/memory/state/reserved\")\n  |> filter(fn: (r) => r[\"host\"] == \"${switch}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "In_Unicast_Packets",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 2, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"gnmi\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"$switch\")\n  |> filter(fn: (r) => r[\"_field\"] == \"/interfaces/interface/state/counters/in_unicast_pkts\")"
    }
   ]
  },
  {
   "title": "Out_Unicast Packets",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 10, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"gnmi\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"$switch\")\n  |> filter(fn: (r) => r[\"_field\"] == \"/interfaces/interface/state/counters/out_unicast_pkts\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "In_Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 18, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"gnmi\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"$switch\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"/interfaces/interface/state/counters/in_errors\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "In_Broadcast packets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 2, "y": 5 },
   "targets": [
    {
     "query": "from(bucket: \"gnmi\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"$switch\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"/interfaces/interface/state/counters/in_broadcast_pkts\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Out_Broadcastpackets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 10, "y": 5 },
   "targets": [
    {
     "query": "from(bucket: \"gnmi\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"$switch\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"/interfaces/interface/state/counters/out_broadcast_pkts\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "In_Discard packets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 2, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"gnmi\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"$switch\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"/interfaces/interface/state/counters/in_discards\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Out_Discard packets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"openconfig\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"$switch\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"/interfaces/interface/state/counters/out_discards\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Out_Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 13, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"gnmi\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"$switch\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"/interfaces/interface/state/counters/out_errors\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}